### ISSUE TITLE
Не могу собрать pdf

### ISSUE THREAD

**Issue by neuromagus** [alexott/sicp-ru#32]
Ругается на отсутствие pscyr.sty. При подстановке руками чудом найденного на просторах www, начинает ругаться
```
LaTeX Font Warning: Font shape `OT1/faq/m/n' undefined
(Font)              using `OT1/cmr/m/n' instead on input line 60.
```
и
```
LaTeX Font Warning: Font shape `T2A/faq/b/n' undefined
(Font)              using `T2A/faq/m/n' instead on input line 71.
```
Ошибок много...
Если игнорировать, то pdf выглядит специфически (КаКтО ТаК и некоторые символы заменены, пострадали примеры кода, это просто одна из первых строк):
![2022-12-14-042505_1920x1080_scrot](https://user-images.githubusercontent.com/63796667/207482145-6eff2a38-3f4e-4e5c-a5eb-bd596768e696.png)

Как собрать инструкции нет. Что нужно из Latex - нет. Release с готовым pdf - нет. Прошу помощи.

**Comment by neuromagus** [comment]
Скачал с инета, плюнув на сборку.

**Comment by alexott** [comment]
сборка даже 16 лет назад была нетривиальной :-)

**Comment by neuromagus** [comment]
Да, несколько пакетов deprecate и убраны из CTAN (как и этот, pscyr). Но на удивление, перевод Пола (pcl) собрался без ошибок и предупреждений. 

Раз такое дело, то прошу подсказать, как учить Lisp в 2022 году (roadmap). Ваш блог прочёл, сразу возникли вопросы, применяете ли Вы в своей практике (ML) диалект Lisp? Я интересуюсь NLP, и как показал openAI с его ботом, не зря.

**Comment by alexott** [comment]
Перевод pcl делался позже, и мы использовали более новые пакеты. 

Сейчас, я персонально не использую Lisp, особенно для работы, хотя использую Clojure для своих проектов. Хотя я знаю некоторых людей кто использует Clojure или Lisp для AI-related проектов. Например, https://twitter.com/mark_l_watson, или были еще активные проекты для clojure (помню по Planet Clojure)
